// <auto-generated />
using System;
using Caffera.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caffera.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Caffera.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espresso and artisan brewed coffees",
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tea, chocolate, and milk based beverages",
                            Name = "Non Coffee"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hearty main dishes and breakfast meals",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light bites and savories to share",
                            Name = "Snack"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet treats, cakes, and pastries",
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("Caffera.Backend.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich and concentrated shot of pure arabica coffee",
                            ImageUrl = "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500",
                            IsAvailable = true,
                            Name = "Espresso Single",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espresso shots diluted with hot water or poured over ice",
                            ImageUrl = "https://images.unsplash.com/photo-1551030173-122aabc4489c?w=500",
                            IsAvailable = true,
                            Name = "Americano Hot / Iced",
                            Price = 22000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Silky steamed milk poured over a double shot of espresso",
                            ImageUrl = "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=500",
                            IsAvailable = true,
                            Name = "Caffè Latte",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Balanced espresso with equal parts steamed milk and dense foam",
                            ImageUrl = "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500",
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh vanilla milk marked with espresso and artisan caramel drizzle",
                            ImageUrl = "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=500",
                            IsAvailable = true,
                            Name = "Caramel Macchiato",
                            Price = 34000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signature iced latte sweetened with authentic Indonesian aren sugar",
                            ImageUrl = "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500",
                            IsAvailable = true,
                            Name = "Palm Sugar Latte (Kopi Aren)",
                            Price = 26000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium Uji matcha whisked with velvety steamed fresh milk",
                            ImageUrl = "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=500",
                            IsAvailable = true,
                            Name = "Matcha Green Tea Latte",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Decadent melted Belgian chocolate with creamy whole milk",
                            ImageUrl = "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=500",
                            IsAvailable = true,
                            Name = "Signature Dark Chocolate",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aromatic black tea infused with bergamot and sweet cream",
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500",
                            IsAvailable = true,
                            Name = "Earl Grey Milk Tea",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Refreshing iced brewed tea infused with sweet whole lychee fruit",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500",
                            IsAvailable = true,
                            Name = "Lychee Iced Tea",
                            Price = 24000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Indonesian style fried rice with smoked chicken, egg, and crackers",
                            ImageUrl = "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500",
                            IsAvailable = true,
                            Name = "Caffèra Fried Rice (Nasi Goreng)",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spaghetti tossed in rich egg parmesan sauce with crispy smoked beef",
                            ImageUrl = "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500",
                            IsAvailable = true,
                            Name = "Creamy Carbonara Pasta",
                            Price = 42000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy golden chicken cutlet served with aromatic Japanese curry sauce",
                            ImageUrl = "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500",
                            IsAvailable = true,
                            Name = "Chicken Katsu Curry Rice",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Juicy beef patty, melted cheddar, caramelized onion in brioche bun",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsAvailable = true,
                            Name = "Classic Beef Burger",
                            Price = 48000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy shoestring fries seasoned with sea salt and truffle dip",
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500",
                            IsAvailable = true,
                            Name = "French Fries with Truffle Mayo",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tender wings glazed with sweet and spicy barbecue sauce",
                            ImageUrl = "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=500",
                            IsAvailable = true,
                            Name = "Crispy Chicken Wings (6 pcs)",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Combo basket of french fries, chicken nuggets, and sausage bites",
                            ImageUrl = "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=500",
                            IsAvailable = true,
                            Name = "Fried Platter Combo",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corn tortilla chips layered with molten cheese sauce and salsa",
                            ImageUrl = "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=500",
                            IsAvailable = true,
                            Name = "Nachos with Guacamole & Cheese",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flaky, buttery French viennoiserie baked fresh every morning",
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500",
                            IsAvailable = true,
                            Name = "Butter Croissant",
                            Price = 22000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy caramelized cheesecake with rich Spanish vanilla notes",
                            ImageUrl = "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500",
                            IsAvailable = true,
                            Name = "Burnt Basque Cheesecake",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espresso soaked ladyfingers layered with whipped mascarpone cream",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500",
                            IsAvailable = true,
                            Name = "Classic Tiramisu",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm dark chocolate brownie served with vanilla ice cream scoop",
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500",
                            IsAvailable = true,
                            Name = "Fudgy Chocolate Brownie",
                            Price = 26000m
                        });
                });

            modelBuilder.Entity("Caffera.Backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Caffera.Backend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 2,
                            Status = "Occupied"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 3,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 4,
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 5,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 6,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 7,
                            Status = "Occupied"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 8,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 8,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 9,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 10,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Caffera.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@caffera.com",
                            Name = "Admin Caffèra",
                            PasswordHash = "$2a$11$f5.yH7p7o1V2iK6vP3kIbe.jX1p/0r9tK8gR6vP2lM1eO2iH7p7o1",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cashier@caffera.com",
                            Name = "Kasir Caffèra",
                            PasswordHash = "$2a$11$f5.yH7p7o1V2iK6vP3kIbe.jX1p/0r9tK8gR6vP2lM1eO2iH7p7o1",
                            Role = "Cashier"
                        });
                });

            modelBuilder.Entity("Caffera.Backend.Models.Menu", b =>
                {
                    b.HasOne("Caffera.Backend.Models.Category", "Category")
                        .WithMany("Menus")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Order", b =>
                {
                    b.HasOne("Caffera.Backend.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Caffera.Backend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caffera.Backend.Models.OrderItem", b =>
                {
                    b.HasOne("Caffera.Backend.Models.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caffera.Backend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Category", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Menu", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Caffera.Backend.Models.Table", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Caffera.Backend.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
